version: 2
jobs:
  buildone:
    machine: true
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/out
      - run: |
            docker login -u "abhinavkishoregv" -p "@kis#0r3"
            docker build -t alpine:latest .
            docker push abhinavkishoregv/alpine:ci
      - persist_to_workspace:
            root: my_workspace
            paths:
              - out
  buildtwo:
    machine: true
    steps:
      - checkout
      - run: echo "A second hello"
      - run: docker pull abhinavkishoregv/alpine:ci
      - run: docker run --rm --name alpine-1 abhinavkishoregv/apline:ci 
      - run: docker exec -d alpine-1 echo "IT worked"
      - run: docker stop alpine-1
workflows:
  version: 2
  one_and_two:
    jobs:
      - buildone
      - buildtwo:
          requires:
            - buildone
