version: 2
jobs:
  buildone:
    machine: true
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/out
      - run: |
            docker login -u "abhinavkishoregv" -p "@Kis#0r3"
            docker build -t abhinavkishoregv/alpine:ci .
            docker push abhinavkishoregv/alpine:ci
      - persist_to_workspace:
            root: my_workspace
            paths:
              - out
  buildtwo:
    machine: true
    steps:
      - checkout
      - run: echo "A second hello"
      - run: docker login -u "abhinavkishoregv" -p "@Kis#0r3"
      - run: docker pull abhinavkishoregv/alpine:ci
      - run: docker pull quay.io/wagoodman/dive
      - run: export CI=true
      - run: docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest abhinavkishoregv/alpine:ci
      
workflows:
  version: 2
  one_and_two:
    jobs:
      - buildone
      - buildtwo:
          requires:
            - buildone
