version: 2
jobs:
  buildone:
    machine: true
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/out
      - run: docker build -t abhinav-alpine:ci .
      - run: docker save -o my_workspace/abhinav-alpine.tar abhinav-alpine:ci
      - persist_to_workspace:
            root: my_workspace
            paths:
               - out
               - abhinav-alpine.tar
  buildtwo:
    machine: true
    steps:
      - checkout
      - attach_workspace:
            at: my_workspace
      - run: echo "A second hello"
      - run: docker load -i my_workspace/abhinav-alpine.tar
      - run: git clone https://github.com/tern-tools/tern.git my_workspace/tern-tools/
      - run: python3 -m venv my_workspace/ternenv
      - run: source my_workspace/ternenv/bin/activate
      - run: pip install tern
      - run: tern report -o my_workspace/a-a-report.txt -i abhinav-alpine:ci
      
      
workflows:
  version: 2
  one_and_two:
    jobs:
      - buildone
      - buildtwo:
          requires:
            - buildone
