version: 2
jobs:
  buildone:
    docker:
     - image: circleci/node:4.8.2
    steps:
     - checkout
     - restore_cache:
       key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
     - run: npm install
     - save_cache:
       key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
         paths:
           - node_modules
