version: 2
jobs:

  build:
    docker:
      - images: circleci/node:4.8.2
      steps:
        - checkout
        - run: echo "A first hello"
  buildone:
    machine: true
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace && touch output.txt
      - run: echo "Trying out workspaces" > my_workspace/out
      - run: docker build -t abhinav-alpine:ci .
      - run: docker save -o my_workspace/abhinav-alpine.tar abhinav-alpine:ci
      - persist_to_workspace:
            root: my_workspace
            paths:
               - out
               - abhinav-alpine.tar
               - output.txt
  buildtwo:
    machine: true
    steps:
      - checkout
      - attach_workspace:
            at: my_workspace
      - run: echo "A second hello"
      - run: docker load -i my_workspace/abhinav-alpine.tar
      - run: git clone https://github.com/tern-tools/tern.git
      - run: docker build -t ternd tern/
      - run: docker pull abhinavkishoregv/alpine:ci
      - run: sh tern/docker_run.sh workdir ternd "report -i debian:buster" >> my_workspace/output.txt
      - run: cat my_workspace/output.txt
      
      
workflows:
  version: 2
  one_and_two:
    jobs:
      - buildone
      - buildtwo:
          requires:
            - buildone

