version: 2
jobs:
  buildone:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "A first hello"
  buildtwo:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "A second hello"


workflows:
  version: 2
  one_and_two:
    jobs:
      - buildone
      - buildtwo
      
