version: 2
jobs:
  buildone:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/out
      - persist_to_workspace:
            root: my_workspace
            paths:
              - out
  buildtwo:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: echo "A second hello"
      - attach_workspace:
          at: my_workspace
      - run: |
          if [[ $(cat my_workspace/out) == "Trying out workspaces" ]]; then
            echo "IT WORKED";
          else
            echo "NOPE!!!";
          fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - buildone
      - buildtwo:
          requires:
            - buildone
